[package]
name = "rustdis"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "rustdis"
path = "src/bin/server.rs"


[dependencies]
bytes = "1.5.0"
# TODO: Use only required features.
tokio = { version = "1.35.0", features = ['full'] }
